print ("meu animal favorito é a ovelha:")

print("O-###-")
print("  |  | #")
print("")
print("eu moro em São Paulo:")
print("")
print("  _|_  ")
print(" |   | ")
print(" |   | ")
print(" |#  |____")
print(" |   |    |")
print(" |   |#   |")
print(" |   |   #|")
